[tool.poetry]
name = "hardware"
version = "0.1.0"
description = ""
authors = ["Saxon Chen <sxa05z@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
pyserial = "^3.5"
flask = "^3.0.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
